2018-10-06 16:34:19,260 INFO: Microblog Startup [in /home/xzhan/Development/MOOC/Microblog/app/__init__.py:47
2018-10-06 16:34:31,803 ERROR: Exception on /edit_profile [POST] [in /home/xzhan/Development/MOOC/Microblog/venv/lib/python3.7/site-packages/flask/app.py:1761
Traceback (most recent call last):
  File "/home/xzhan/Development/MOOC/Microblog/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/home/xzhan/Development/MOOC/Microblog/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/xzhan/Development/MOOC/Microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/xzhan/Development/MOOC/Microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/xzhan/Development/MOOC/Microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/xzhan/Development/MOOC/Microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/xzhan/Development/MOOC/Microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/xzhan/Development/MOOC/Microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/xzhan/Development/MOOC/Microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/xzhan/Development/MOOC/Microblog/app/routes.py", line 104, in edit_profile
    db.session.commit()
  File "/home/xzhan/Development/MOOC/Microblog/venv/lib/python3.7/site-packages/sqlalchemy/orm/scoping.py", line 153, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/xzhan/Development/MOOC/Microblog/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 943, in commit
    self.transaction.commit()
  File "/home/xzhan/Development/MOOC/Microblog/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 467, in commit
    self._prepare_impl()
  File "/home/xzhan/Development/MOOC/Microblog/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 447, in _prepare_impl
    self.session.flush()
  File "/home/xzhan/Development/MOOC/Microblog/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2254, in flush
    self._flush(objects)
  File "/home/xzhan/Development/MOOC/Microblog/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2380, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/xzhan/Development/MOOC/Microblog/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/xzhan/Development/MOOC/Microblog/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/home/xzhan/Development/MOOC/Microblog/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2344, in _flush
    flush_context.execute()
  File "/home/xzhan/Development/MOOC/Microblog/venv/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 391, in execute
    rec.execute(self)
  File "/home/xzhan/Development/MOOC/Microblog/venv/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 556, in execute
    uow
  File "/home/xzhan/Development/MOOC/Microblog/venv/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 177, in save_obj
    mapper, table, update)
  File "/home/xzhan/Development/MOOC/Microblog/venv/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 768, in _emit_update_statements
    execute(statement, multiparams)
  File "/home/xzhan/Development/MOOC/Microblog/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/home/xzhan/Development/MOOC/Microblog/venv/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/xzhan/Development/MOOC/Microblog/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/xzhan/Development/MOOC/Microblog/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/home/xzhan/Development/MOOC/Microblog/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/home/xzhan/Development/MOOC/Microblog/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/xzhan/Development/MOOC/Microblog/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 248, in reraise
    raise value.with_traceback(tb)
  File "/home/xzhan/Development/MOOC/Microblog/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/home/xzhan/Development/MOOC/Microblog/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.username [SQL: 'UPDATE user SET username=?, about_me=? WHERE user.id = ?'] [parameters: ('lola', 'Hi this is John from Ann Arbor!', 1)] (Background on this error at: http://sqlalche.me/e/gkpj)
2018-10-06 16:55:37,136 INFO: Microblog Startup [in /home/xzhan/Development/MOOC/Microblog/app/__init__.py:47
2018-10-06 16:55:43,536 ERROR: Exception on /edit_profile [GET] [in /home/xzhan/Development/MOOC/Microblog/venv/lib/python3.7/site-packages/flask/app.py:1761
Traceback (most recent call last):
  File "/home/xzhan/Development/MOOC/Microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/xzhan/Development/MOOC/Microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/xzhan/Development/MOOC/Microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/xzhan/Development/MOOC/Microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/xzhan/Development/MOOC/Microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/xzhan/Development/MOOC/Microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/xzhan/Development/MOOC/Microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/xzhan/Development/MOOC/Microblog/app/routes.py", line 99, in edit_profile
    form = EditProfileForm()
  File "/home/xzhan/Development/MOOC/Microblog/venv/lib/python3.7/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'original_username'
2018-10-06 16:55:47,916 ERROR: Exception on /edit_profile [GET] [in /home/xzhan/Development/MOOC/Microblog/venv/lib/python3.7/site-packages/flask/app.py:1761
Traceback (most recent call last):
  File "/home/xzhan/Development/MOOC/Microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/xzhan/Development/MOOC/Microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/xzhan/Development/MOOC/Microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/xzhan/Development/MOOC/Microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/xzhan/Development/MOOC/Microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/xzhan/Development/MOOC/Microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/xzhan/Development/MOOC/Microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/xzhan/Development/MOOC/Microblog/app/routes.py", line 99, in edit_profile
    form = EditProfileForm()
  File "/home/xzhan/Development/MOOC/Microblog/venv/lib/python3.7/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'original_username'
2018-10-06 16:57:23,451 INFO: Microblog Startup [in /home/xzhan/Development/MOOC/Microblog/app/__init__.py:47
2018-10-06 16:58:44,931 INFO: Microblog Startup [in /home/xzhan/Development/MOOC/Microblog/app/__init__.py:47
